name: Hackerrank CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Tree Height solutions
      run: ./hackerrank/test.sh "data_structures/trees/tree-height"
